name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Авторизация в GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Lissa0628
          password: ${{ secrets.CR_PAT }}

      # Шаг 3: Сборка Docker образа
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/Lissa0628/chetdven:${{ github.sha }} .

      # Шаг 4: Отправка образа в реестр
      - name: Push Docker image
        run: |
          docker push ghcr.io/Lissa0628/chetdven:${{ github.sha }}
          
